version: "3"

services:
  client:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8900:8900
    command: sh -c "npm config set registry https://registry.npm.taobao.org && npm install && npm start"
